path_config             : "./results/step_2/convnext/folder_config"
epoch                   : -1

model_name              : "convnextv2"
config_name             : 'base'
gpu_index               : "0"
dim_embed               : 1024
debug                   : False

eval_after              : 0
save_ckpt               : True
save_after              : 0

batch_size_sim          : 4
batch_size_train        : 4
batch_size_eval         : 4
batch_size_test         : 4

dataset                 : "apacc"
normalization           : "imagenet"
img_size                : 384
path_data               : "./data/SCP"
device                  : 'cpu'

lr_head                 : 0.0001
lr                      : 0.000002
weight_decay            : 0.01
scheduler               : True
frequency_reweight      : False
epochs                  : 40
loss                    : 'ce'
num_classes             : 2

display_loss_freq       : 20
validate_every          : 1
save_every              : 1
eval_valid              : True

num_workers             : 16
num_workers_valid       : 16
num_workers_test        : 16
persistent_workers      : True
persistent_workers_val  : True
persistent_workers_test : True

name_scheduler          : 'constant'
use_scheduler           : True
num_warmup_steps        : 3000

save_dir                : './results/step_2/convnext'

path_convnext           : './data/model/convnextv2-base-22k-384'

proba_flip              : 0.5
proba_crop              : 0.5
proba_rotate            : 0.3
proba_elastic           : 0.2

use_loss_ce             : True
use_weight_ce           : True
use_loss_focal          : False
gamma                   : 2.0
